Repository prgrms-be-devcourse/NBE2_2_Team9, pull requests merged in 2024-10, with the labels that each got.

#45 fix/get-medication
  src/main/java/com/mednine/pillbuddy/domain/medicationApi/controller/MedicationApiController.java
  src/main/java/com/mednine/pillbuddy/domain/medicationApi/service/MedicationApiService.java
  src/main/java/com/mednine/pillbuddy/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: 🐞 BugFix, 🔨 Refactor

#48 39:[FEAT] 회원 프로필 업로드
  src/main/java/com/mednine/pillbuddy/domain/record/entity/Record.java
  src/main/java/com/mednine/pillbuddy/domain/user/entity/User.java
  src/main/java/com/mednine/pillbuddy/domain/user/profile/controller/ProfileController.java
  src/main/java/com/mednine/pillbuddy/domain/user/profile/dto/ProfileUploadDto.java
  src/main/java/com/mednine/pillbuddy/domain/user/profile/entity/Image.java
  src/main/java/com/mednine/pillbuddy/domain/user/profile/repository/ImageRepository.java
  src/main/java/com/mednine/pillbuddy/domain/user/profile/service/ProfileService.java
  src/main/java/com/mednine/pillbuddy/domain/user/profile/service/uploader/CaregiverProfileUploader.java
  src/main/java/com/mednine/pillbuddy/domain/user/profile/service/uploader/CaretakerProfileUploader.java
  src/main/java/com/mednine/pillbuddy/domain/user/profile/service/uploader/ProfileUploader.java
  src/main/java/com/mednine/pillbuddy/global/exception/ErrorCode.java
  src/main/java/com/mednine/pillbuddy/global/util/UploadUtils.java
  src/main/resources/application.yml
  src/test/java/com/mednine/pillbuddy/domain/user/profile/service/ProfileServiceTest.java
  src/test/java/com/mednine/pillbuddy/domain/user/profile/service/uploader/CaregiverProfileUploaderTest.java
  src/test/java/com/mednine/pillbuddy/domain/user/profile/service/uploader/CaretakerProfileUploaderTest.java
  src/test/java/com/mednine/pillbuddy/global/util/UploadUtilsTest.java
  src/test/resources/application.yml
Labels: ✨ Feature, ✅ Test

#51 50:[FIX] 사용자 레포지토리 충돌 해결
  src/main/java/com/mednine/pillbuddy/domain/user/caretaker/repository/CareTakerRepository.java
  src/main/java/com/mednine/pillbuddy/domain/user/caretaker/repository/CaretakerRepository.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 🐞 BugFix

#53 52:[FEAT] 사용자 및 보호자 엔티티의 조회 기능 구현
  src/main/java/com/mednine/pillbuddy/domain/user/caregiver/repository/CaregiverRepository.java
  src/main/java/com/mednine/pillbuddy/domain/user/caretaker/repository/CaretakerRepository.java
  src/main/java/com/mednine/pillbuddy/domain/user/controller/UserController.java
  src/main/java/com/mednine/pillbuddy/domain/user/dto/UserDto.java
  src/main/java/com/mednine/pillbuddy/domain/user/dto/UserType.java
  src/main/java/com/mednine/pillbuddy/domain/user/service/UserService.java
  src/main/java/com/mednine/pillbuddy/global/util/UploadUtils.java
  src/test/java/com/mednine/pillbuddy/domain/user/service/UserServiceTest.java
  src/test/java/com/mednine/pillbuddy/global/util/UploadUtilsTest.java
  src/test/resources/application.yml
Labels: ✨ Feature, ✅ Test

#58 55:[FEAT] 회원 수정 및 삭제 기능
  src/main/java/com/mednine/pillbuddy/domain/user/controller/UserController.java
  src/main/java/com/mednine/pillbuddy/domain/user/dto/JoinDto.java
  src/main/java/com/mednine/pillbuddy/domain/user/dto/UserPasswordUpdateDto.java
  src/main/java/com/mednine/pillbuddy/domain/user/dto/UserUpdateDto.java
  src/main/java/com/mednine/pillbuddy/domain/user/entity/User.java
  src/main/java/com/mednine/pillbuddy/domain/user/profile/entity/Image.java
  src/main/java/com/mednine/pillbuddy/domain/user/profile/service/uploader/CaregiverProfileUploader.java
  src/main/java/com/mednine/pillbuddy/domain/user/profile/service/uploader/CaretakerProfileUploader.java
  src/main/java/com/mednine/pillbuddy/domain/user/service/UserService.java
  src/main/java/com/mednine/pillbuddy/global/util/UploadUtils.java
  src/test/java/com/mednine/pillbuddy/domain/user/profile/service/uploader/CaregiverProfileUploaderTest.java
  src/test/java/com/mednine/pillbuddy/domain/user/profile/service/uploader/CaretakerProfileUploaderTest.java
  src/test/java/com/mednine/pillbuddy/domain/user/service/UserServiceTest.java
  src/test/java/com/mednine/pillbuddy/global/util/UploadUtilsTest.java
Labels: ✨ Feature, ✅ Test

#60 59:[REFACTOR] 회원 테스트 코드 리팩토링
  src/test/java/com/mednine/pillbuddy/domain/user/service/MyUserDetailsServiceTest.java
  src/test/java/com/mednine/pillbuddy/domain/user/service/UserServiceTest.java
Labels: 🔨 Refactor

#61 40: [FEAT] 약 정보 기록 초기값 세팅 및 복용 기록 수정
  src/main/java/com/mednine/pillbuddy/domain/record/dto/RecordDTO.java
  src/main/java/com/mednine/pillbuddy/domain/record/entity/Record.java
  src/main/java/com/mednine/pillbuddy/domain/record/repository/RecordRepository.java
  src/main/java/com/mednine/pillbuddy/domain/record/service/RecordService.java
  src/main/java/com/mednine/pillbuddy/domain/record/service/RecordServiceImpl.java
  src/main/java/com/mednine/pillbuddy/domain/user/caretaker/controller/CaretakerController.java
  src/main/java/com/mednine/pillbuddy/global/exception/ErrorCode.java
  src/test/java/com/mednine/pillbuddy/domain/record/service/RecordServiceImplTest.java
  src/test/java/com/mednine/pillbuddy/domain/user/caretaker/controller/CaretakerControllerTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#64 62: [FEAT] 알림 시간 수정
  src/main/java/com/mednine/pillbuddy/domain/notification/controller/NotificationController.java
  src/main/java/com/mednine/pillbuddy/domain/notification/dto/NotificationDTO.java
  src/main/java/com/mednine/pillbuddy/domain/notification/entity/Notification.java
  src/main/java/com/mednine/pillbuddy/domain/notification/service/NotificationService.java
  src/main/java/com/mednine/pillbuddy/domain/record/RecordRepository.java
  src/main/java/com/mednine/pillbuddy/domain/record/repository/RecordRepository.java
  src/test/java/com/mednine/pillbuddy/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/mednine/pillbuddy/domain/notification/service/NotificationServiceTest.java
Labels: ✨ Feature

#67 46:[REFACTOR] 약 정보 검색
  src/main/java/com/mednine/pillbuddy/domain/medicationApi/controller/MedicationApiController.java
  src/main/java/com/mednine/pillbuddy/domain/medicationApi/dto/MedicationDTO.java
  src/main/java/com/mednine/pillbuddy/domain/medicationApi/dto/MedicationForm.java
  src/main/java/com/mednine/pillbuddy/domain/medicationApi/service/MedicationApiService.java
  src/test/java/com/mednine/pillbuddy/domain/medicationApi/controller/MedicationApiControllerTest.java
  src/test/java/com/mednine/pillbuddy/domain/medicationApi/service/MedicationApiServiceTest.java
Labels: 🔨 Refactor

#68 [FEAT] 알림 삭제
  src/main/java/com/mednine/pillbuddy/domain/notification/controller/NotificationController.java
  src/main/java/com/mednine/pillbuddy/domain/notification/service/NotificationService.java
  src/test/java/com/mednine/pillbuddy/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/mednine/pillbuddy/domain/notification/service/NotificationServiceTest.java
Labels: ✨ Feature

#66 63:[REFACTOR] JWT 인증 로직 리팩토링
  src/main/java/com/mednine/pillbuddy/domain/user/service/UserService.java
  src/main/java/com/mednine/pillbuddy/global/exception/ErrorCode.java
  src/main/java/com/mednine/pillbuddy/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/mednine/pillbuddy/global/jwt/JwtTokenProvider.java
  src/test/java/com/mednine/pillbuddy/domain/user/service/UserServiceTest.java
Labels: 🔨 Refactor

#70 69:[FEAT] 리프레시 토큰 관리 기능
  build.gradle
  src/main/java/com/mednine/pillbuddy/domain/user/controller/AuthController.java
  src/main/java/com/mednine/pillbuddy/domain/user/controller/UserController.java
  src/main/java/com/mednine/pillbuddy/domain/user/service/AuthService.java
  src/main/java/com/mednine/pillbuddy/domain/user/service/UserService.java
  src/main/java/com/mednine/pillbuddy/global/config/RedisConfig.java
  src/main/java/com/mednine/pillbuddy/global/jwt/JwtTokenProvider.java
  src/main/java/com/mednine/pillbuddy/global/redis/RedisUtils.java
  src/main/resources/application.yml
  src/test/java/com/mednine/pillbuddy/domain/user/service/AuthServiceTest.java
  src/test/java/com/mednine/pillbuddy/domain/user/service/UserServiceTest.java
  src/test/resources/application.yml
Labels: ✨ Feature, ✅ Test

#74 73: [FEAT] 스프링 시큐리티 권한 설정
  src/main/java/com/medinine/pillbuddy/domain/medicationApi/controller/MedicationApiController.java
  src/main/java/com/medinine/pillbuddy/domain/notification/controller/NotificationController.java
  src/main/java/com/medinine/pillbuddy/domain/user/caregiver/controller/CaregiverController.java
  src/main/java/com/medinine/pillbuddy/domain/user/caretaker/controller/CaretakerController.java
  src/main/java/com/medinine/pillbuddy/domain/user/controller/AuthController.java
  src/main/java/com/medinine/pillbuddy/domain/user/controller/UserController.java
  src/main/java/com/medinine/pillbuddy/domain/userMedication/controller/UserMedicationController.java
  src/main/java/com/medinine/pillbuddy/global/config/SecurityConfig.java
Labels: ✨ Feature, 🔨 Refactor

#76 75:[FIX] Swagger API 경로 시큐리티 설정
  src/main/java/com/medinine/pillbuddy/global/config/SecurityConfig.java
Labels: 🐞 BugFix

#78 77: [FIX] 약 정보 검색
  src/main/java/com/medinine/pillbuddy/domain/medicationApi/dto/MedicationDTO.java
  src/main/java/com/medinine/pillbuddy/domain/medicationApi/entity/Medication.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#82 80:[DOCS] README 작성
  README.md
  docs/git convention.md
Labels: 📃 Docs
